#!/usr/bin/env node
/**
 * Copies what the demo platform needs from .env into AWS Secrets Manager, before
 * an AWS day, from the laptop as splitx-devops:
 *
 *   npm run aws:secrets             write splitx/demo/app and splitx/demo/platform
 *   npm run aws:secrets -- --check  say what would be written, by key name, and what is missing
 *
 * What goes where is decided in scripts/lib/demo-secrets.mjs. Two values nobody
 * has to choose are generated into .env on the first run: ORIGIN_VERIFY_SECRET
 * (the header CloudFront sends the load balancer) and NEXUS_ADMIN_PASSWORD.
 *
 * Values are never printed, never put on a command line and never written to a
 * file but .env. They reach AWS only in the body of a signed HTTPS request
 * (scripts/lib/aws-sigv4.mjs), with the CLI's credentials held in memory.
 * aws-down deletes both secrets with no recovery window: .env keeps the originals.
 */
import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { appendFileSync, readFileSync } from 'node:fs';
import { ALERT_KEYS } from './lib/alertmanager-config.mjs';
import { signRequest } from './lib/aws-sigv4.mjs';
import { APP_SECRET, PLATFORM_SECRET, demoSecrets } from './lib/demo-secrets.mjs';

const REGION = process.env.AWS_REGION || 'ap-south-1';
const CHECK = process.argv.includes('--check');

function fail(message) {
    console.error('aws:secrets: ' + message);
    process.exit(1);
}

// ── Values nobody has to choose, generated once into .env ──
const generated = [];
function ensureEnv(key, comment) {
    if (process.env[key]?.trim()) return;
    const value = randomBytes(32).toString('hex');
    if (!CHECK) appendFileSync('.env', `\n# ${comment} (generated by npm run aws:secrets)\n${key}=${value}\n`);
    process.env[key] = value;
    generated.push(key);
}
ensureEnv('ORIGIN_VERIFY_SECRET', 'CloudFront sends this to the load balancer, and the app refuses requests without it');
ensureEnv('NEXUS_ADMIN_PASSWORD', 'The Nexus admin password on the demo platform (user admin)');
if (generated.length) console.log(`${CHECK ? 'Would generate' : 'Generated'} into .env: ${generated.join(', ')}`);

let secrets;
try {
    secrets = demoSecrets(process.env, { alertmanagerTemplate: readFileSync('monitoring/alertmanager/alertmanager.yaml', 'utf8') });
} catch (error) {
    fail(error.message);
}
const { missing, app, platform } = secrets;
if (missing.length) {
    fail('.env is missing: ' + missing.join(', ')
        + (missing.includes('DEMO_DATABASE_URL') ? '. DEMO_DATABASE_URL is a Neon branch with the schema and no data (docs/DECISIONS.md, D-091).' : ''));
}
console.log(`${APP_SECRET}: ${Object.keys(app).sort().join(', ')}`);
console.log(`${PLATFORM_SECRET}: ${Object.keys(platform).sort().join(', ')}`);
if (!app.GITHUB_ID) console.log('  (no AWS_GITHUB_ID in .env: the EKS site will not offer GitHub sign-in)');
if (!platform.JENKINS_GITHUB_TOKEN) console.log('  (no JENKINS_GITHUB_TOKEN in .env: Jenkins on EKS reads GitHub anonymously and reports nothing back)');
const unsetAlertKeys = ALERT_KEYS.filter((key) => !process.env[key]?.trim());
if (unsetAlertKeys.length) console.log(`  (no ${unsetAlertKeys.join(', ')} in .env: alerts fire on EKS but are not emailed)`);
if (CHECK) {
    console.log('--check: nothing written.');
    process.exit(0);
}

// ── Credentials of the CLI's identity, in memory only ──
const exported = spawnSync('aws', ['configure', 'export-credentials', '--format', 'process'], { encoding: 'utf8' });
if (exported.error || exported.status !== 0) fail('no AWS credentials: ' + (exported.stderr || exported.error?.message || '').trim());
const { AccessKeyId, SecretAccessKey, SessionToken } = JSON.parse(exported.stdout);
const credentials = { accessKeyId: AccessKeyId, secretAccessKey: SecretAccessKey, sessionToken: SessionToken };

async function secretsManager(action, payload) {
    const host = `secretsmanager.${REGION}.amazonaws.com`;
    const body = JSON.stringify(payload);
    const signed = signRequest({
        method: 'POST',
        host,
        headers: { 'content-type': 'application/x-amz-json-1.1', 'x-amz-target': `secretsmanager.${action}` },
        body,
    }, credentials, { region: REGION, service: 'secretsmanager' });
    // fetch sets Host from the URL itself (the same value that was signed).
    const headers = { ...signed };
    delete headers.host;
    const response = await fetch(`https://${host}/`, { method: 'POST', headers, body });
    const text = await response.text();
    return { ok: response.ok, status: response.status, answer: text ? JSON.parse(text) : {} };
}

const reason = ({ status, answer }) => `${answer.__type ?? 'HTTP ' + status}: ${answer.Message ?? answer.message ?? ''}`.trim();

async function write(name, contents, description) {
    const secretString = JSON.stringify(contents);
    const put = await secretsManager('PutSecretValue', { SecretId: name, SecretString: secretString });
    if (put.ok) return 'updated';
    if (!String(put.answer.__type).endsWith('ResourceNotFoundException')) fail(`${name}: ${reason(put)}`);
    const created = await secretsManager('CreateSecret', {
        Name: name,
        Description: description,
        SecretString: secretString,
        Tags: [{ Key: 'project', Value: 'splitx' }, { Key: 'stack', Value: 'platform' }],
    });
    if (!created.ok) fail(`${name}: ${reason(created)}`);
    return 'created';
}

for (const [name, contents, description] of [
    [APP_SECRET, app, 'The SplitX app on the demo platform (splitx-secrets), from .env by npm run aws:secrets'],
    [PLATFORM_SECRET, platform, 'Grafana, Alertmanager, Jenkins and Nexus on the demo platform, from .env by npm run aws:secrets'],
]) {
    const outcome = await write(name, contents, description);
    console.log(`${name}: ${outcome}, ${Object.keys(contents).length} keys`);
}
console.log(`\nIn ${REGION}. The External Secrets Operator reads them on the cluster; aws-down deletes them.`);
