apiVersion: v1
kind: ConfigMap
metadata:
  name: splitx-config
  namespace: splitx
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  PORT: "3000"
  METRICS_TOKEN: "" # Set via K8s Secret in production
