apiVersion: v1
kind: Service
metadata:
  name: splitx-service
  namespace: splitx
  labels:
    app: splitx
spec:
  type: ClusterIP
  selector:
    app: splitx
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
